"""add settings table

Revision ID: 1d83762e0e29
Revises: 54f96f84c283
Create Date: 2026-08-07 13:02:15.734525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d83762e0e29'
down_revision: Union[str, Sequence[str], None] = '54f96f84c283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS settings (
            key   VARCHAR NOT NULL PRIMARY KEY,
            value VARCHAR
        )
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_table('settings')
    # ### end Alembic commands ###
