"""initial schema

Revision ID: 54f96f84c283
Revises: 
Create Date: 2026-06-05 09:16:13.555904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f96f84c283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('symbols',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('time_slots',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('approaches',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('entry_models',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('approach_name', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['approach_name'], ['approaches.name'], ),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True
    )
    op.create_table('trades',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.String(), nullable=True),
        sa.Column('symbol', sa.String(), nullable=True),
        sa.Column('time_slot', sa.String(), nullable=True),
        sa.Column('approach', sa.String(), nullable=True),
        sa.Column('entry_model', sa.String(), nullable=True),
        sa.Column('r_gain', sa.Float(), nullable=True),
        sa.Column('size', sa.Float(), nullable=True),
        sa.Column('time_to_tp', sa.Integer(), nullable=True),
        sa.Column('time_to_sl', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('date', sa.String(), nullable=True),
        sa.Column('time_slot', sa.String(), nullable=True),
        sa.Column('pregame', sa.Text(), nullable=True),
        sa.Column('checkin', sa.Text(), nullable=True),
        sa.Column('post_review', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('date', 'time_slot')
    )
    op.create_table('reflections',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('week_start', sa.String(), nullable=True),
        sa.Column('reflection', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('week_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_table('entry_models')
    op.drop_table('trades')
    op.drop_table('session_logs')
    op.drop_table('reflections')
    op.drop_table('approaches')
    op.drop_table('time_slots')
    op.drop_table('symbols')
    # ### end Alembic commands ###
