"""initial schema

Revision ID: 54f96f84c283
Revises: 
Create Date: 2026-06-05 09:16:13.555904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f96f84c283'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approach_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['approach_name'], ['approaches.name'], ),
    sa.PrimaryKeyConstraint('id'),
    if_not_exists=True
    )
    op.add_column('trades', sa.Column('entry_model', sa.String(), nullable=True))
   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 
    op.drop_column('trades', 'entry_model')    
    op.drop_table('entry_models')
    # ### end Alembic commands ###
